name: unspash

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - 8443:80
    env_file:
      - .env
    volumes:
      - nginx:/usr/src/nginx
    networks:
      - app_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - backend:/usr/src/backend
    networks:
      - app_network


volumes:
  nginx:
    name: nginx
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/nginx/
  backend:
    name: backend
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/backend/

networks:
  app_network:
    name: app_network
    driver: bridge